---
sidebar: sidebar 
permalink: reference-new.html 
keywords: 'what"s new, new, features, release notes, enhancements' 
summary: Cloud Volumes ONTAP 9.7에는 몇 가지 새로운 기능과 개선 사항이 포함되어 있습니다. 
---
= Cloud Volumes ONTAP 9.7의 새로운 기능
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP 9.7에는 몇 가지 새로운 기능과 개선 사항이 포함되어 있습니다.

최신 버전의 Cloud Manager에는 추가 기능과 개선 사항도 포함되어 있습니다. 를 참조하십시오 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/whats-new.html["Cloud Manager 릴리즈 노트"^] 를 참조하십시오.



== 9.7 P6(2020년 8월 15일)

Cloud Volumes ONTAP용 9.7 P6 패치 릴리스는 현재 Cloud Manager 3.8 이상을 통해 제공되고 있습니다. Cloud Manager에서 기존 시스템을 이 패치 릴리즈로 업그레이드하라는 메시지가 표시됩니다. https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.7P6["P6 패치에서 해결된 버그 목록을 봅니다"^] (NetApp Support 사이트 로그인 필요).



== 추가 용량을 위한 다중 BYOL 라이센스(2020년 8월 3일)

이제 Cloud Volumes ONTAP BYOL 시스템에 여러 개의 라이센스를 구매하여 368TiB 이상의 용량을 할당할 수 있습니다. 예를 들어, 2개의 라이센스를 구입하여 최대 736TiB의 용량을 Cloud Volumes ONTAP에 할당할 수 있습니다. 또는 4개의 라이센스를 구입하여 최대 1.4개의 PiB를 구입할 수 있습니다.

단일 노드 시스템 또는 HA 쌍에 대해 구매할 수 있는 라이센스 수는 무제한입니다.

디스크 제한만으로는 용량 제한에 도달하지 못할 수 있습니다. 를 사용하면 디스크 제한을 초과할 수 있습니다 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-data-tiering.html["비활성 데이터를 오브젝트 스토리지로 계층화"^]. 디스크 제한에 대한 자세한 내용은 본 릴리즈 노트의 스토리지 제한을 참조하십시오.

https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-manage-node-licenses.html["Cloud Volumes ONTAP에 시스템 라이센스를 추가하는 방법에 대해 알아보십시오"^].



== 9.7 P5 in AWS(2020년 7월 27일)

Cloud Volumes ONTAP 9.7 P5는 현재 AWS에서 제공되고 있습니다. 이 패치 릴리즈에는 버그 수정 및 새로운 EC2 인스턴스 유형 지원이 포함되어 있습니다.

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.7P5["P5 패치에서 해결된 버그 목록을 봅니다"^] (NetApp Support 사이트 로그인 필요).



=== 새로운 EC2 인스턴스 유형 지원

이제 Cloud Volumes ONTAP는 Premium 및 BYOL 라이센스를 통해 다음과 같은 EC2 인스턴스 유형을 지원합니다.

* c5n.9xLarge
* c5n.18xLarge




== Azure의 9.7 P5(2020년 7월 20일)

Cloud Volumes ONTAP 9.7 P5는 이제 Microsoft Azure에서 사용할 수 있습니다. 이 패치 릴리스에는 버그 수정 및 새 VM 유형에 대한 지원이 포함되어 있습니다.

https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.7P5["P5 패치에서 해결된 버그 목록을 봅니다"^] (NetApp Support 사이트 로그인 필요).



=== Ultra SSD VNVRAM으로 새로운 VM 유형 지원

이제 Cloud Volumes ONTAP는 프리미엄 또는 BYOL 라이센스를 가진 단일 노드 시스템에서 다음과 같은 VM 유형을 지원합니다.

* Standard_E32s_v3
* Standard_E48s_v3


E32s_v3 VM 유형에는 가 사용됩니다 https://docs.microsoft.com/en-us/azure/virtual-machines/windows/disks-enable-ultra-ssd["울트라급 SSD"^] VNVRAM의 경우, 더 나은 쓰기 성능을 제공합니다.

현재 이러한 VM 유형에 대한 지원은 미국 정부 버지니아, 미국 남부 중부 및 미국 서부 지역에서 제공됩니다.



== AWS에서 다중 스토리지 VM 지원(2020년 7월 16일)

Cloud Volumes ONTAP 9.7은 이제 AWS에서 여러 SVM(스토리지 VM)을 지원합니다.

BYOL(Bring Your Own License)을 사용하는 경우 C5, M5 및 R5 인스턴스 유형에서 여러 스토리지 VM이 지원됩니다. 지원되는 스토리지 VM 수는 다음과 같습니다.

* 단일 노드 시스템이 있는 스토리지 VM 12개
* HA 쌍을 지원하는 스토리지 VM 8개


기본적으로 Cloud Volumes ONTAP로 구성된 첫 번째 스토리지 VM 외에 각 additional_data-serving_storage VM에 대해 애드온 라이센스가 필요합니다. SVM 애드온 라이센스를 받으려면 어카운트 팀에 문의하십시오.

DR(재해 복구)에 대해 구성하는 스토리지 VM에는 추가 라이센스(무료)가 필요하지 않지만 스토리지 VM 제한에 대해 카운트됩니다.

예를 들어, HA 쌍에서 8개의 데이터 서비스 스토리지 VM을 사용하는 경우 이 제한에 도달하여 추가 스토리지 VM을 생성할 수 없습니다. 재해 복구를 위해 8개의 스토리지 VM이 구성된 또 다른 HA 쌍에서도 마찬가지입니다. 이 제한에 도달했으므로 추가 스토리지 VM을 생성할 수 없습니다.

추가 스토리지 VM은 System Manager 또는 CLI를 통해 생성해야 합니다.



== Azure의 독일 Sovereign 지역은 더 이상 지원되지 않습니다(2020년 6월 26일).

Cloud Volumes ONTAP는 더 이상 다음 Azure 지역에서 지원되지 않습니다.

* 독일 중앙(소버린권)
* 독일 북동부(Sovereign)


NetApp은 독일 공공 지역에서 Cloud Volumes ONTAP를 지속적으로 지원합니다.

* 독일 북부(공공)
* 독일 웨스트 센트럴(퍼블릭)


https://cloud.netapp.com/cloud-volumes-global-regions["지원되는 Azure 지역의 전체 목록을 참조하십시오"^].



== 9.7 P4(2020년 6월 2일)

Cloud Volumes ONTAP용 9.7 P4 패치 릴리즈는 이제 Cloud Manager 3.8 이상을 통해 제공됩니다. Cloud Manager에서 기존 시스템을 이 패치 릴리즈로 업그레이드하라는 메시지가 표시됩니다. https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.7P4["P4 패치에서 해결된 버그 목록을 봅니다"^] (NetApp Support 사이트 로그인 필요).



== 9.7 P3(2020년 5월 2일)

Cloud Volumes ONTAP용 9.7 P3 패치 릴리스는 현재 Cloud Manager 3.8 이상을 통해 제공됩니다. Cloud Manager에서 기존 시스템을 이 패치 릴리즈로 업그레이드하라는 메시지가 표시됩니다. https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.7P3["P3 패치에서 해결된 버그 목록을 봅니다"^] (NetApp Support 사이트 로그인 필요).



== 9.7 P2(2020년 4월 8일)

Cloud Volumes ONTAP용 9.7 P2 패치 릴리즈가 현재 Cloud Manager 3.8 이상을 통해 제공되고 있습니다. Cloud Manager에서 기존 시스템을 이 패치 릴리즈로 업그레이드하라는 메시지가 표시됩니다. https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.7P2["P2 패치에서 해결된 버그 목록을 봅니다"^] (NetApp Support 사이트 로그인 필요).



== Google Cloud의 디스크 용량 증가(2020년 3월 13일)

이제 Google Cloud에서 프리미엄 또는 BYOL 라이센스를 사용할 때 최대 256TiB의 영구 디스크를 Cloud Volumes ONTAP에 연결할 수 있습니다. 이 용량은 64TB에서 가능합니다.

이전과 마찬가지로, 오브젝트 스토리지에 영구 디스크를 데이터 계층화와 결합하여 Premium 및 BYOL의 최대 시스템 용량은 368TiB에 도달할 수 있습니다.

시스템당 최대 데이터 디스크 수도 124개로 증가했습니다.

* link:reference-configs-gcp.html["Google Cloud에서 지원되는 Cloud Volumes ONTAP 구성에 대해 자세히 알아보십시오"]
* link:reference-limits-gcp.html["Google Cloud의 스토리지 제한사항을 검토하십시오"]




== 9.7 P1(2020년 3월 6일)

Cloud Volumes ONTAP용 9.7 P1 패치 릴리즈는 이제 Cloud Manager 3.8 이상을 통해 제공됩니다. Cloud Manager에서 기존 시스템을 이 패치 릴리즈로 업그레이드하라는 메시지가 표시됩니다. https://mysupport.netapp.com/site/products/all/details/cloud-volumes-ontap/downloads-tab/download/62632/9.7P1["P1 패치에서 해결된 버그 목록을 봅니다"^] (NetApp Support 사이트 로그인 필요).



== AWS 업데이트(2020년 2월 16일)

NetApp은 새로운 EC2 인스턴스에 대한 지원과 지원되는 데이터 디스크 수의 변경을 발표했습니다.



=== 새 인스턴스 지원

프리미엄 또는 BYOL 라이센스를 사용하는 경우 Cloud Volumes ONTAP 9.7에서 다음과 같은 몇 가지 새로운 EC2 인스턴스 유형이 지원됩니다.

* c5.9xLarge
* c5d.18xLarge^1^
* m5d.8xLarge^1^
* m5d.12xLarge^1^
* m5.16xLarge
* r5.8xLarge
* r5.12xLarge^2^


^1^ 이러한 인스턴스 유형에는 Cloud Volumes ONTAP이 _Flash Cache_로 사용하는 로컬 NVMe 스토리지가 포함됩니다. https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-flash-cache.html["자세한 정보"^].

^2^ r5.12xLarge 인스턴스 유형은 지원 가능성의 알려진 제한 사항이 있습니다. 패닉이 발생하여 노드가 예기치 않게 재부팅되는 경우 시스템에서 문제 해결에 사용되는 핵심 파일을 수집하지 못하고 문제의 근본 원인을 해결하지 못할 수 있습니다. 고객은 위험 및 제한된 지원 약관에 동의하며 이 조건이 발생할 경우 모든 지원 책임을 집니다.

https://aws.amazon.com/ec2/instance-types/["이러한 EC2 인스턴스 유형에 대해 자세히 알아보십시오"^].

link:reference-configs-aws.html["AWS에서 지원되는 9.7 구성에 대해 자세히 알아보십시오"].



=== 지원되는 데이터 디스크

이제 C5, M5 및 R5 인스턴스에 대해 데이터 디스크 하나를 적게 지원합니다. 단일 노드 시스템의 경우 22개의 데이터 디스크가 지원됩니다. HA 쌍의 경우 노드당 19개의 데이터 디스크가 지원됩니다.

link:reference-limits-aws.html["AWS의 스토리지 제한에 대해 자세히 알아보십시오"].



== Azure의 DS15_v2 지원(2020년 2월 12일)

이제 Cloud Volumes ONTAP는 단일 노드 시스템과 HA 쌍 모두에서 Azure의 DS15_v2 가상 머신 유형으로 지원됩니다.

https://docs.microsoft.com/en-us/azure/virtual-machines/linux/sizes-memory#dsv2-series-11-15["DSv2 시리즈에 대해 자세히 알아보십시오"^].

link:reference-configs-azure.html["Azure에서 지원되는 9.7 구성에 대해 자세히 알아보십시오"].



== 9.7 GA(2020년 2월 10일)

Cloud Volumes ONTAP 9.7의 GA(General Availability) 릴리즈는 이제 AWS 및 Google Cloud에서 사용할 수 있습니다. GA 릴리스에는 버그 수정이 포함되어 있습니다. Cloud Manager에서 기존 시스템을 이 릴리즈로 업그레이드하라는 메시지가 표시됩니다.



== Azure용 9.7 D1(2020년 1월 29일)

Cloud Volumes ONTAP 9.7 D1은 이제 Microsoft Azure에서 사용할 수 있습니다.

Cloud Volumes ONTAP 9.7 및 이전 버전에서 문제가 발견되었습니다. 이 문제는 Azure 가상 시스템이 다시 시작되는 상황에서 Cloud Volumes ONTAP가 성공적으로 시작되지 않을 수 있습니다.

이 문제는 9.7 D1 이상에서 해결되었습니다. 가능한 한 빨리 최신 Cloud Volumes ONTAP 버전으로 업그레이드할 것을 적극 권장합니다.

문의 사항이 있는 경우 제품 내 채팅 또는 을 통해 문의해 주십시오 https://www.netapp.com/us/contact-us/support.aspx[].



== 9.7 RC1(2019년 12월 16일)

Cloud Volumes ONTAP 9.7 RC1은 현재 AWS, Azure 및 Google 클라우드 플랫폼에서 제공됩니다. 에 도입된 기능 외에도 https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["ONTAP 9.7"^]이 Cloud Volumes ONTAP 릴리스에는 다음이 포함됩니다.

* <<Flash Cache support in Azure>>
* <<Fix for Azure NIC detach events>>




=== Azure에서 Flash Cache 지원

이제 Cloud Volumes ONTAP는 Azure에서 단일 노드, BYOL 시스템을 통해 Standard_L8s_v2 VM 유형을 지원합니다. 이 VM 유형에는 Cloud Volumes ONTAP가 _Flash Cache_로 사용하는 로컬 NVMe 스토리지가 포함됩니다.

Flash Cache는 최근에 읽은 사용자 데이터와 NetApp 메타데이터의 실시간 지능형 캐싱을 통해 데이터 액세스 속도를 높입니다. 데이터베이스, 이메일, 파일 서비스를 비롯한 랜덤 읽기 집약적인 워크로드에 효과적입니다.

이 VM 유형을 사용하여 새 시스템을 구축하거나 기존 시스템을 수정하여 이 VM 유형을 사용하면 Flash Cache를 자동으로 활용할 수 있습니다.

https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-flash-cache.html["데이터 압축 제한 등 Cloud Volumes ONTAP에서 Flash Cache를 사용하는 방법에 대해 자세히 알아보십시오"^].



=== Azure NIC 분리 이벤트 수정

이 릴리즈에서는 Azure NIC 분리 이벤트에서 Cloud Volumes ONTAP 노드 재부팅의 문제를 해결합니다. Cloud Volumes ONTAP는 이러한 이벤트를 보다 원활하게 처리하고 서비스를 중단시키지 않습니다. Cloud Volumes ONTAP HA 쌍에서는 Azure 고정 유지 관리 이벤트로부터 테이크오버/반환 시퀀스를 계속 수행하지만, 이 시간 동안 발생할 수 있는 NIC 분리에서는 후속 재부팅이 없습니다.



== 노트 업그레이드

* Cloud Volumes ONTAP 업그레이드는 Cloud Manager에서 완료해야 합니다. System Manager 또는 CLI를 사용하여 Cloud Volumes ONTAP를 업그레이드해서는 안 됩니다. 이렇게 하면 시스템 안정성에 영향을 줄 수 있습니다.
* 9.6 릴리즈에서 Cloud Volumes ONTAP 9.7로 업그레이드할 수 있습니다. Cloud Manager에서 기존 Cloud Volumes ONTAP 9.6 시스템을 9.7 릴리즈로 업그레이드하라는 메시지가 표시됩니다.
+
http://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-updating-ontap-cloud.html["Cloud Manager에서 알림을 받을 때 업그레이드하는 방법에 대해 알아보십시오"^].

* 단일 노드 시스템을 업그레이드하면 시스템이 최대 25분 동안 오프라인 상태로 전환되고 이 동안 I/O가 중단됩니다.
* HA 2노드 업그레이드는 무중단으로 I/O를 업그레이드할 수 있으며 이 무중단 업그레이드 프로세스 중에 각 노드가 동시 업그레이드되어 클라이언트에 I/O를 계속 제공합니다.

