---
sidebar: sidebar 
permalink: reference-limits-aws.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM, ebs 
summary: Cloud Volumes ONTAP는 AWS에서 스토리지 구성을 제한하여 안정적인 운영 기능을 제공합니다. 최상의 성능을 위해 시스템을 최대 값으로 구성하지 마십시오. 
---
= AWS에서의 스토리지 제한
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP는 안정적인 운영을 제공하기 위해 스토리지 구성에 제한이 있습니다. 최상의 성능을 위해 시스템을 최대 값으로 구성하지 마십시오.



== 라이센스별 최대 시스템 용량

Cloud Volumes ONTAP 시스템의 최대 시스템 용량은 라이센스에 따라 결정됩니다. 최대 시스템 용량에는 디스크 기반 스토리지와 데이터 계층화에 사용되는 오브젝트 스토리지가 포함됩니다. NetApp은 이 제한을 초과하지 않습니다.

일부 HA 구성에서는 디스크 하나만 사용하여 용량 제한에 도달하지 않도록 합니다. 이 경우 를 통해 용량 제한에 도달할 수 있습니다 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-data-tiering.html["비활성 데이터를 오브젝트 스토리지로 계층화"^]. 자세한 내용은 아래의 용량 및 디스크 제한을 참조하십시오.

[cols="25,75"]
|===
| 라이센스 | 최대 시스템 용량(디스크 + 오브젝트 스토리지) 


| 프리모늄 | 500GiB 


| PAYGO 탐색 | 2TiB(데이터 계층화는 Explore에서 지원되지 않음) 


| PAYGO 표준 | 10TiB 


| PAYGO 프리미엄 | 368TiB 


| 노드 기반 라이센스 | 라이센스당 368TiB입니다 


| 용량 기반 라이센스 | 2 PiB 
|===


===== HA의 경우 노드당 또는 전체 HA 쌍의 라이센스 용량 제한이 있습니까?

용량 제한은 전체 HA 쌍에 대한 것입니다. 노드 단위로 표시되지 않습니다. 예를 들어, Premium 라이센스를 사용하는 경우 두 노드 간에 최대 368TiB의 용량을 가질 수 있습니다.



===== AWS의 HA 시스템에서 미러링된 데이터는 용량 제한에 따라 계산됩니까?

아니요, 그렇지 않습니다. AWS HA 쌍의 데이터는 노드 간에 동기식으로 미러링되므로 장애 발생 시 데이터를 사용할 수 있습니다. 예를 들어, 노드 A에서 8TiB 디스크를 구매하는 경우 Cloud Manager는 미러링된 데이터에 사용되는 노드 B에도 8TiB 디스크를 할당합니다. 16TiB의 용량을 프로비저닝한 경우 라이센스 제한에서 8TiB만 가능합니다.



== EC2 인스턴스별로 디스크 및 계층화가 제한됩니다

Cloud Volumes ONTAP는 EBS 볼륨을 디스크로 사용하며 최대 디스크 크기는 16TiB입니다. 아래 섹션에는 EC2 인스턴스 유형 중 많은 수의 디스크 제한이 서로 다르기 때문에 EC2 인스턴스 유형별 디스크 및 계층화 제한이 나와 있습니다. 또한 디스크 제한은 단일 노드 시스템과 HA 쌍 간에 다릅니다.

아래의 디스크 제한은 사용자 데이터를 포함하는 디스크에만 적용됩니다. 이 제한에는 부팅 디스크 및 루트 디스크가 포함되지 않습니다.


NOTE: 이제 Cloud Volumes ONTAP BYOL 시스템에 여러 노드 기반 라이센스를 구입하여 368TiB 이상의 용량을 할당할 수 있습니다. 단일 노드 시스템 또는 HA 쌍에 대해 구매할 수 있는 라이센스 수는 무제한입니다. 디스크 제한만으로는 용량 제한에 도달하지 못할 수 있습니다. 를 사용하면 디스크 제한을 초과할 수 있습니다 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-data-tiering.html["비활성 데이터를 오브젝트 스토리지로 계층화"^]. https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-manage-node-licenses.html["Cloud Volumes ONTAP에 시스템 라이센스를 추가하는 방법에 대해 알아보십시오"^].



=== 프리미엄 라이센스가 있는 단일 노드

[cols="18,18,32,32"]
|===
| 인스턴스 패밀리 | 노드당 최대 디스크 수입니다 | 디스크만 사용할 경우 최대 시스템 용량 | 디스크 및 데이터 계층화를 통한 최대 시스템 용량 


| C5, M5 및 R5 인스턴스 | 22 | 352TiB | 368TiB 


| C4, M4 및 R4 인스턴스 | 34 | 368TiB | 368TiB 
|===


=== 노드 기반 라이센스가 있는 단일 노드

[cols="18,18,16,16,16,16"]
|===
| 인스턴스 패밀리 | 노드당 최대 디스크 수입니다 2+| 하나의 라이센스로 최대 시스템 용량을 지원합니다 2+| 여러 라이센스가 있는 최대 시스템 용량 


2+|  | * 디스크만 사용 * | * 디스크 + 데이터 계층화 * | * 디스크만 사용 * | * 디스크 + 데이터 계층화 * 


| C5, M5 및 R5 인스턴스 | 22 | 352TiB | 368TiB | 352TiB | 368TiB x 각 라이센스 


| C4, M4 및 R4 인스턴스 | 34 | 368TiB | 368TiB | 544TiB | 368TiB x 각 라이센스 
|===


=== 용량 기반 라이센스가 있는 단일 노드

[cols="18,18,32,32"]
|===
| 인스턴스 패밀리 | 노드당 최대 디스크 수입니다 | 디스크만 사용할 경우 최대 시스템 용량 | 디스크 및 데이터 계층화를 통한 최대 시스템 용량 


| C5, M5 및 R5 인스턴스 | 22 | 352TiB | 2 PiB 


| C4, M4 및 R4 인스턴스 | 34 | 544TiB | 2 PiB 
|===


=== HA는 Premium 라이센스와 페어링합니다

[cols="18,18,32,32"]
|===
| 인스턴스 패밀리 | 노드당 최대 디스크 수입니다 | 디스크만 사용할 경우 최대 시스템 용량 | 디스크 및 데이터 계층화를 통한 최대 시스템 용량 


| C5, M5 및 R5 인스턴스 | 19 | 304TiB | 368TiB 


| C4, M4 및 R4 인스턴스 | 31 | 368TiB | 368TiB 
|===


=== HA는 노드 기반 라이센스와 페어링합니다

[cols="18,18,16,16,16,16"]
|===
| 인스턴스 패밀리 | 노드당 최대 디스크 수입니다 2+| 하나의 라이센스로 최대 시스템 용량을 지원합니다 2+| 여러 라이센스가 있는 최대 시스템 용량 


2+|  | * 디스크만 사용 * | * 디스크 + 데이터 계층화 * | * 디스크만 사용 * | * 디스크 + 데이터 계층화 * 


| C5, M5 및 R5 인스턴스 | 19 | 304TiB | 368TiB | 304TiB | 368TiB x 각 라이센스 


| C4, M4 및 R4 인스턴스 | 31 | 368TiB | 368TiB | 4,96TiB | 368TiB x 각 라이센스 
|===


=== HA는 용량 기반 라이센스와 페어링합니다

[cols="18,18,32,32"]
|===
| 인스턴스 패밀리 | 노드당 최대 디스크 수입니다 | 디스크만 사용할 경우 최대 시스템 용량 | 디스크 및 데이터 계층화를 통한 최대 시스템 용량 


| C5, M5 및 R5 인스턴스 | 19 | 304TiB | 2 PiB 


| C4, M4 및 R4 인스턴스 | 31 | 4,96TiB | 2 PiB 
|===


== 애그리게이트 제한

Cloud Volumes ONTAP는 AWS 볼륨을 디스크로 사용하고 이를 _aggregate_로 그룹화합니다. Aggregate는 볼륨에 스토리지를 제공합니다.

[cols="2*"]
|===
| 매개 변수 | 제한 


| 최대 애그리게이트 수입니다 | 단일 노드: 디스크 한계 HA 쌍과 동일: 노드 ^1^에서 18 


| 최대 애그리게이트 크기입니다 | 96TiB 물리적 용량^2^ 


| 애그리게이트당 디스크 수 | 1-6^3^ 


| 애그리게이트당 최대 RAID 그룹 수 | 1 
|===
참고:

. HA Pair의 두 노드에서 19개의 애그리게이트를 만들 수 없습니다. 그렇게 할 경우 데이터 디스크 제한이 초과되기 때문입니다.
. 애그리게이트 용량 한도는 애그리게이트를 구성하는 디스크를 기준으로 합니다. 이 제한에는 데이터 계층화에 사용되는 오브젝트 스토리지가 포함되지 않습니다.
. Aggregate의 모든 디스크는 동일한 크기여야 합니다.




== 논리적 스토리지 제한입니다

[cols="22,22,56"]
|===
| 논리적 스토리지 | 매개 변수 | 제한 


| SVM(스토리지 VM) * | 최대 Cloud Volumes ONTAP 수(HA 쌍 또는 단일 노드)  a| 
* BYOL * 을 사용하는 C5, M5 및 R5 인스턴스 * BYOL(Bring Your Own License) 방식으로 C5, M5 및 R5 인스턴스 유형 지원:

* 단일 노드 시스템이 있는 스토리지 VM 12개
* HA 쌍을 지원하는 스토리지 VM 8개



NOTE: 스토리지 VM이 전체 Cloud Volumes ONTAP 시스템(HA 쌍 또는 단일 노드)에 걸쳐 있음

기본적으로 Cloud Volumes ONTAP와 함께 제공되는 첫 번째 스토리지 VM 외에 _data-serving_SVM을 추가할 때마다 애드온 라이센스가 필요합니다. SVM 애드온 라이센스를 받으려면 어카운트 팀에 문의하십시오.

DR(재해 복구)에 대해 구성하는 스토리지 VM에는 추가 라이센스(무료)가 필요하지 않지만 스토리지 VM 제한에 대해 카운트됩니다. ^1,2^

* 다른 모든 구성 * 하나의 데이터 서비스 스토리지 VM과 재해 복구에 사용되는 하나의 대상 스토리지 VM이 지원됩니다. ^2^

스토리지 VM은 전체 Cloud Volumes ONTAP 시스템(HA 쌍 또는 단일 노드)에 걸쳐 있습니다.



.2+| * 파일 * | 최대 크기 | 16TiB 


| 볼륨당 최대 | 볼륨 크기에 따라 다르며 최대 20억 개까지 가능합니다 


| FlexClone 볼륨 * | 계층적 복제 깊이 ^3^ | 499 


.3+| * FlexVol 볼륨 * | 노드당 최대 | 500입니다 


| 최소 크기 | 20MB 


| 최대 크기 | 100TiB 


| * qtree * | FlexVol 볼륨당 최대 | 4,995 


| Snapshot 복사본 * | FlexVol 볼륨당 최대 | 1,023 
|===
참고:

. 예를 들어, HA 쌍에서 8개의 데이터 서비스 스토리지 VM을 사용하는 경우 이 제한에 도달하여 추가 스토리지 VM을 생성할 수 없습니다. 재해 복구를 위해 8개의 스토리지 VM이 구성된 또 다른 HA 쌍에서도 마찬가지입니다. 이 제한에 도달했으므로 추가 스토리지 VM을 생성할 수 없습니다.
. 소스 스토리지 VM에 운영 중단이 발생할 경우 데이터 액세스를 위해 대상 스토리지 VM을 활성화할 수 있습니다. Cloud Manager는 스토리지 VM 재해 복구에 대한 설정 또는 오케스트레이션 지원을 제공하지 않습니다. System Manager 또는 CLI를 사용해야 합니다.
+
** https://library.netapp.com/ecm/ecm_get_file/ECMLP2839856["SVM 재해 복구 준비 Express 가이드"^]
** https://library.netapp.com/ecm/ecm_get_file/ECMLP2839857["SVM 재해 복구 익스프레스 가이드 를 참조하십시오"^]


. 계층적 클론 깊이는 단일 FlexVol 볼륨에서 생성할 수 있는 FlexClone 볼륨의 중첩 계층 구조의 최대 깊이입니다.




== iSCSI 스토리지 제한입니다

[cols="3*"]
|===
| iSCSI 스토리지 | 매개 변수 | 제한 


.4+| LUN * | 노드당 최대 | 1,024 


| 최대 LUN 매핑 수입니다 | 1,024 


| 최대 크기 | 16TiB 


| 볼륨당 최대 | 512 


| Igroup * 을 선택합니다 | 노드당 최대 | 256 


.2+| * 이니시에이터 * | 노드당 최대 | 512 


| igroup당 최대 | 128 


| * iSCSI 세션 * | 노드당 최대 | 1,024 


.2+| LIF * | 포트당 최대 | 32 


| 최대 Per 포트셋 | 32 


| * 포트 세트 * | 노드당 최대 | 256 
|===